# Datalab 2 - Sprint 2
## groep 6 : 
- Ardjun Debi - Tewarie (25032895)
- Azfar Mohab Ali (25026356)
- Tesja Kartomo (25035193)
- Shelby Gibbs (18005055)

### import and connection with the db
Hier maken we **verbinding** met de database dat is in **./database.sqlite**

In [16]:
import sqlite3
import pandas as pd


db_path = "./assets/database.sqlite"
conn = sqlite3.connect(db_path)

print(f"Database connectie is gemaakt met: {db_path}.")

Database connectie is gemaakt met: ./assets/database.sqlite.

## Functie : show_query
Met deze functie zorg je ervoor dat je alleen hoeft **show_query(var)** hoeft te doen en het geeft de rijen en de kolommen aan en **show_head_query** zorgt ervoor een kleine deel

In [ ]:
def show_query(query):
    """
    Deze functie print de output van de SQL query uit.
    """
    df = pd.read_sql_query(query, conn)
    display(df)

def show_head_query(query):
    """
    Deze functie print de output van de SQL query uit. maar alleen de eerste rij.
    """
    df = pd.read_sql_query(query, conn)
    display(df.head(1))

## Stap 0: Structuur van de database bekijken

- **Stap 0.1:** Bekijk alle tabellen in de database.  
- **Stap 0.2 – 0.8:** Bekijk de kolommen van de belangrijkste tabellen (`Player_Attributes`, `Player`, `Match`, `League`, `Country`, `Team`, `Team_Attributes`) om te begrijpen welke data beschikbaar is.

In [18]:
#stap 0: Kijk naar de structuur van de db
#stap 0.1: alle tabellen uit de database
print("All tabellen uit de database:")
show_query(
    """
    SELECT name as tabelnamen
    FROM sqlite_master
    WHERE type='table';
    """
)
#stap 0.2: alle kolommen uit de tabel: Player_Attributes
print("alle kolommen uit de tabel: Player_Attributes:")
show_head_query(
    """
    SELECT * from Player_Attributes
    """
)
#stap 0.3: alle kolommen uit de tabel: Player
print("alle kolommen uit de tabel: Player:")
show_head_query(
    """
    SELECT * from Player
    """
)
#stap 0.4: alle kolommen uit de tabel Match
print("alle kolommen uit de tabel: Match:")
show_head_query(
    """
    SELECT * from Match
    """
)
#stap 0.5: alle kolommen uit de tabel: League
print("alle kolommen uit de tabel: League:")
show_head_query(
    """
    SELECT * from League
    """
)
#stap 0.6 alle kolommen uit de tabel: Country
print("alle kolommen uit de tabel: Country:")
show_head_query(
    """
    SELECT * from Country
    """
)
#stap 0.7: alle kolommen uit de tabel: Team
print("alle kolommen uit de tabel: Team:")
show_head_query(
    """
    SELECT * from Team
    """
)

#stap 0.8: alle kolommen uit de tabel: Team_Attributes
print("alle kolommen uit de tabel: Team_Attributes:")
show_head_query(
    """
    SELECT * from Team_Attributes
    """
)

All tabellen uit de database:

          tabelnamen
0    sqlite_sequence
1  Player_Attributes
2             Player
3              Match
4             League
5            Country
6               Team
7    Team_Attributes

alle kolommen uit de tabel: Player_Attributes:

Empty DataFrame
Columns: [id, player_fifa_api_id, player_api_id, date, overall_rating, potential, preferred_foot, attacking_work_rate, defensive_work_rate, crossing, finishing, heading_accuracy, short_passing, volleys, dribbling, curve, free_kick_accuracy, long_passing, ball_control, acceleration, sprint_speed, agility, reactions, balance, shot_power, jumping, stamina, strength, long_shots, aggression, interceptions, positioning, vision, penalties, marking, standing_tackle, sliding_tackle, gk_diving, gk_handling, gk_kicking, gk_positioning, gk_reflexes]
Index: []

[0 rows x 42 columns]

alle kolommen uit de tabel: Player:

Empty DataFrame
Columns: [id, player_api_id, player_name, player_fifa_api_id, birthday, height, weight]
Index: []

alle kolommen uit de tabel: Match:

Empty DataFrame
Columns: [id, country_id, league_id, season, stage, date, match_api_id, home_team_api_id, away_team_api_id, home_team_goal, away_team_goal, home_player_X1, home_player_X2, home_player_X3, home_player_X4, home_player_X5, home_player_X6, home_player_X7, home_player_X8, home_player_X9, home_player_X10, home_player_X11, away_player_X1, away_player_X2, away_player_X3, away_player_X4, away_player_X5, away_player_X6, away_player_X7, away_player_X8, away_player_X9, away_player_X10, away_player_X11, home_player_Y1, home_player_Y2, home_player_Y3, home_player_Y4, home_player_Y5, home_player_Y6, home_player_Y7, home_player_Y8, home_player_Y9, home_player_Y10, home_player_Y11, away_player_Y1, away_player_Y2, away_player_Y3, away_player_Y4, away_player_Y5, away_player_Y6, away_player_Y7, away_player_Y8, away_player_Y9, away_player_Y10, away_player_Y11, home_player_1, home_player_2, home_player_3, home_player_4, home_player_5, home_player_6, home_player_7, home_player_8, home_player_9, home_player_10, home_player_11, away_player_1, away_player_2, away_player_3, away_player_4, away_player_5, away_player_6, away_player_7, away_player_8, away_player_9, away_player_10, away_player_11, goal, shoton, shotoff, foulcommit, card, cross, corner, possession, B365H, B365D, B365A, BWH, BWD, BWA, IWH, IWD, IWA, LBH, LBD, LBA, PSH, PSD, PSA, ...]
Index: []

[0 rows x 115 columns]

alle kolommen uit de tabel: League:

Empty DataFrame
Columns: [id, country_id, name]
Index: []

alle kolommen uit de tabel: Country:

Empty DataFrame
Columns: [id, name]
Index: []

alle kolommen uit de tabel: Team:

Empty DataFrame
Columns: [id, team_api_id, team_fifa_api_id, team_long_name, team_short_name]
Index: []

alle kolommen uit de tabel: Team_Attributes:

Empty DataFrame
Columns: [id, team_fifa_api_id, team_api_id, date, buildUpPlaySpeed, buildUpPlaySpeedClass, buildUpPlayDribbling, buildUpPlayDribblingClass, buildUpPlayPassing, buildUpPlayPassingClass, buildUpPlayPositioningClass, chanceCreationPassing, chanceCreationPassingClass, chanceCreationCrossing, chanceCreationCrossingClass, chanceCreationShooting, chanceCreationShootingClass, chanceCreationPositioningClass, defencePressure, defencePressureClass, defenceAggression, defenceAggressionClass, defenceTeamWidth, defenceTeamWidthClass, defenceDefenderLineClass]
Index: []

[0 rows x 25 columns]

## Stap 1: team_api_id van Barcelona vinden

- **Stap 1:** Zoek in de tabel **Team** naar de `team_api_id` van **FC Barcelona**. Deze identifier gebruiken we later om wedstrijden van dit team te vinden.

In [22]:
# stap 1: vind de team_api_id van FC Barcelona
show_query("""
SELECT team_long_name, team_api_id
FROM Team
WHERE team_long_name = 'FC Barcelona';
""")

  team_long_name  team_api_id
0   FC Barcelona         8634

## Stap 2: Matches van Barcelona vinden

- **Stap 2:** Zoekt naar wedstrijden waarin Barcelona speelt door `team_api_id` (8634) in de tabel **Match** te filteren. Hierbij kijken we zowel naar `home_team_api_id` als `away_team_api_id`.

In [ ]:
# stap 2: vind de matches door middel van team_api_id van barcelona
show_query("""
SELECT
  Match.id,
  Match.season,
  Match.country_id,
  Match.league_id,
  Match.home_team_api_id,
  Match.away_team_api_id
FROM Match
WHERE Match.home_team_api_id = 8634
   OR Match.away_team_api_id = 8634
LIMIT 5;
          
""")

      id     season  country_id  league_id  home_team_api_id  away_team_api_id
0  21521  2008/2009       21518      21518              8388              8634
1  21535  2008/2009       21518      21518              8634             10281
2  21547  2008/2009       21518      21518              8479              8634
3  21550  2008/2009       21518      21518              8634              8305
4  21564  2008/2009       21518      21518              8302              8634

## Stap 3: League van Barcelona bepalen

- **Stap 3.1:** Zoek de `league_id` van een wedstrijd waarin Barcelona speelt.  
- **Stap 3.2:** Zoek de `country_id` van deze wedstrijd.  
- **Stap 3.3:** Gebruik de `country_id` om de naam van de **League** te vinden.

In [ ]:
# stap 3: vind de league_id's en de naam van de league van de matches van barcelona
# stap 3.1: vind de league id
show_query(
"""
SELECT Match.league_id
FROM Match
WHERE Match.home_team_api_id = 8634 OR Match.away_team_api_id = 8634
LIMIT 1;
""")

# stap 3.2: vind eerste de country id om makkelijjker te zoeken naar de name van de League
show_query(
"""
SELECT Match.country_id
FROM Match
WHERE home_team_api_id = 8634
LIMIT 1
"""
)
# stap 3.3 vind nu de naam van de league:
show_query(
"""
SELECT League.Name
FROM League
WHERE country_id = 21518
LIMIT 1
"""
)

   league_id
0      21518

   country_id
0       21518

              name
0  Spain LIGA BBVA

## Belangrijke variablen
- Team : **Barcelona**
- `Team_api_id`, `home_team_api_id`, `away_team_api_id` : 8634
- `Country_id`, `League_id` : 21518
- `League.Name` : Spain LIGA BBVA

## Relaties:
### Tabel met relaties:
| Kolom| Van tabel | Naar tabel | Naar kolom | Beschrijving|
| ------------------ | ----------------- | ---------- | ------------------ | ----------------------------------------------------------------------- |
| country_id | League| Country| id | Geeft aan in welk land de **competitie plaatsvindt**. |
| country_id | Match | Country| id | Geeft aan in welk land de **wedstrijd gespeeld** wordt. |
| league_id| Match | League | id | **Verbindt** een wedstrijd aan de competitie waarin deze gespeeld wordt.|
| home_team_api_id | Match | Team | team_api_id| Verwijst naar het team dat de **thuiswedstrijd** speelt.|
| away_team_api_id | Match | Team | team_api_id| Verwijst naar het team dat de **uitwedstrijd** speelt.|
| player_api_id| Player_Attributes | Player | player_api_id| **Verbindt** de spelers attributen met een specifieke speler.|
| player_fifa_api_id | Player_Attributes | Player | player_fifa_api_id | Alternatieve identifier uit FIFA dat die attributen aan een speler **koppelt**. |
| team_api_id| Team_Attributes | Team | team_api_id| **Verbindt** team attributen met een specifiek team. |
| team_fifa_api_id | Team_Attributes | Team | team_fifa_api_id | FIFA identifier die team attributen **koppelt** aan een team.|
| away_player_1| Match | Player | player_api_id| Eerste speler van het **uit team** in de wedstrijd. |
| away_player_2| Match | Player | player_api_id| Tweede speler van het **uit team** in de wedstrijd. |
| away_player_3| Match | Player | player_api_id| Derde speler van het **uit team** in de wedstrijd.|
| away_player_4| Match | Player | player_api_id| Vierde speler van het **uit team** in de wedstrijd. |
| away_player_5| Match | Player | player_api_id| Vijfde speler van het **uit team** in de wedstrijd. |
| away_player_6| Match | Player | player_api_id| Zesde speler van het **uit team** in de wedstrijd.|
| away_player_7| Match | Player | player_api_id| Zevende speler van het **uit team** in de wedstrijd.|
| away_player_8| Match | Player | player_api_id| Achtste speler van het **uit team** in de wedstrijd.|
| away_player_9| Match | Player | player_api_id| Negende speler van het **uit team** in de wedstrijd.|
| away_player_10 | Match | Player | player_api_id| Tiende speler van het **uit team** in de wedstrijd. |
| away_player_11 | Match | Player | player_api_id| Elfde speler van het **uit team** in de wedstrijd.|
| home_player_1| Match | Player | player_api_id| Eerste speler van het **thuis team** in de wedstrijd. |
| home_player_2| Match | Player | player_api_id| Tweede speler van het **thuis team** in de wedstrijd. |
| home_player_3| Match | Player | player_api_id| Derde speler van het **thuis team** in de wedstrijd.|
| home_player_4| Match | Player | player_api_id| Vierde speler van het **thuis team** in de wedstrijd. |
| home_player_5| Match | Player | player_api_id| Vijfde speler van het **thuis team** in de wedstrijd. |
| home_player_6| Match | Player | player_api_id| Zesde speler van het **thuis team** in de wedstrijd.|
| home_player_7| Match | Player | player_api_id| Zevende speler van het **thuis team** in de wedstrijd.|
| home_player_8| Match | Player | player_api_id| Achtste speler van het **thuis team** in de wedstrijd.|
| home_player_9| Match | Player | player_api_id| Negende speler van het **thuis team** in de wedstrijd.|
| home_player_10 | Match | Player | player_api_id| Tiende speler van het **thuis team** in de wedstrijd. |
| home_player_11 | Match | Player | player_api_id| Elfde speler van het **thuis team** in de wedstrijd.|

### Samengevat:
Elke wedstrijd is gekoppeld aan een competitie via `league_id` en aan twee teams via `home_team_api_id` en `away_team_api_id`, die verwijzen naar de tabel **Team**.

De spelers die in een wedstrijd spelen staan in de kolommen `home_player_1` t/m `home_player_11` en `away_player_1` t/m `away_player_11`. Deze verwijzen naar de tabel **Player**.

De tabellen `Player_Attributes` en `Team_Attributes` bevatten extra informatie over **spelers** en **teams** en zijn gekoppeld via hun **API identifiers**.

testing