# Datalab 2 - Sprint 2
## groep 6 : 
- Ardjun Debi - Tewarie (25032895)
- Azfar Mohab Ali (25026356)
- Tesja Kartomo (25035193)
- Shelby Gibbs (18005055)

### import and connection with the db
Hier maken we **verbinding** met de database dat is in **./database.sqlite**

In [12]:
import sqlite3
import pandas as pd


db_path = "./assets/database.sqlite"
conn = sqlite3.connect(db_path)

print(f"Database connectie is gemaakt met: {db_path}.")

Database connectie is gemaakt met: ./assets/database.sqlite.

## Functie : show_query
Met deze functie zorg je ervoor dat je alleen hoeft **show_query(var)** hoeft te doen en het geeft de rijen en de kolommen aan en **show_head_query** zorgt ervoor een kleine deel

In [13]:
def show_query(query):
    """
    Deze functie print de output van de SQL query uit.

    """
    df = pd.read_sql_query(query, conn)
    display(df)

def show_head_query(query):
    """
    Deze functie print de output van de SQL query uit. maar alleen de eerste rij.
    """
    df = pd.read_sql_query(query, conn)
    display(df.head(10))

## Stap 1 – team_api_id vinden

Zoekt in de tabel **Team** naar FC Barcelona om de **team_api_id** te vinden.

Resultaat: **team_api_id = 8634**

## Stap 2 – Wedstrijden bekijken

Gebruik **team_api_id = 8634** in de tabel **Match** om wedstrijden te vinden waarin Barcelona speelt als thuis- of uitteam.

In [14]:
# stap 1: Find the team row for short name BAR
show_head_query("""
SELECT team_long_name, team_api_id
FROM Team
WHERE team_long_name = 'FC Barcelona';
""")

  team_long_name  team_api_id
0   FC Barcelona         8634

In [15]:
# stap 2: vind de matches door middel van team_api_id van barcelona
show_head_query("""
SELECT
  Match.id,
  Match.season,
  Match.country_id,
  Match.league_id,
  Match.home_team_api_id,
  Match.away_team_api_id
FROM Match
WHERE Match.home_team_api_id = 8634
   OR Match.away_team_api_id = 8634
""")

      id     season  country_id  league_id  home_team_api_id  away_team_api_id
0  21521  2008/2009       21518      21518              8388              8634
1  21535  2008/2009       21518      21518              8634             10281
2  21547  2008/2009       21518      21518              8479              8634
3  21550  2008/2009       21518      21518              8634              8305
4  21564  2008/2009       21518      21518              8302              8634
5  21572  2008/2009       21518      21518              8634             10267
6  21578  2008/2009       21518      21518              8634              8633
7  21593  2008/2009       21518      21518             10205              8634
8  21603  2008/2009       21518      21518              8634              8661
9  21614  2008/2009       21518      21518              8371              8634